name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: |
        sudo apt-get update
        sudo apt install -y binutils gcc xorriso nasm g++ grub-common python3
    
    - name: Build
      run: |
        python3 scripts/setup.py
        python3 scripts/run.py build

    - name: Clean
      run: |
        python3 scripts/run.py clean
