name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install requirements
      run: |
        sudo apt-get update 
        sudo apt install -y binutils gcc xorriso nasm g++ grub-common python3 mtools
    
    - name: Setup
      run: |
        python3 scripts/setup.py
    
    - name: Build
      run: |
        python3 scripts/run.py build

    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: ISO Image
        path: AlveniaOS.iso
        retention-days: 7
    
    - name: Clean
      run: |
        python3 scripts/run.py clean
